#!/bin/sh

### BEGIN INIT INFO
# Provides:       gsc
# Required-Start: $local_fs $remote_fs $syslog
# Required-Stop:  $local_fs $remote_fs $syslog
# Default-Start:  2 3 4 5
# Default-Stop:   0 1 6
# Description:    Handles actions for gaming session controller (gsc)
### END INIT INFO

DAEMON=gsc
DAEMON_PATH=/usr/bin
CONFIG_PATH=/usr/share/gsc
PIDFILE=/var/run/$DAEMON.pid
COUNTFILE=/var/run/$DAEMON.counts.xml
LOGFILE=/var/log/$DAEMON.log
DAEMON_OPTIONS=" -d --config-file=$CONFIG_PATH/gsc.config.xml --counter-file=$COUNTFILE --logger-config-file=$CONFIG_PATH/gsc.logger.xml --log-file=$LOGFILE"
MSGDEV=/dev/kmsg

case "$1" in
  start)
	# start the daemon 
	/sbin/start-stop-daemon --start --quiet --make-pidfile --pidfile $PIDFILE --background --startas /bin/bash -- -c "exec $DAEMON_PATH/$DAEMON $DAEMON_OPTIONS"
	/bin/echo "$DAEMON started" > $MSGDEV
	;;
  stop)
	# stop the daemon
	/sbin/start-stop-daemon --stop --quiet --make-pidfile --pidfile $PIDFILE --startas /bin/bash -- -c "exec $DAEMON_PATH/$DAEMON $DAEMON_OPTIONS"
	/bin/echo "$DAEMON stopped" > $MSGDEV
	;;
  restart|force-reload)
	$0 stop
	/bin/sleep 1
	$0 start
	;;
  *)
	N=/etc/init.d/$DAEMON
	/bin/echo "Usage: $N {start|stop|restart}" >&2
	exit 1
	;;
esac

exit 0
