name: build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      
    - name: Prepare tooling
      run: |
        sudo apt-get update
        sudo apt-get -y install gcc cmake make liblog4cxx-dev python3-pip python3-setuptools python3-wheel
        pip3 install conan
        export PATH=$PATH:$HOME/.local/bin
        conan profile new default
        conan profile update settings.compiler.libcxx=libstdc++11 default
        mkdir build
        
    - name: Get dependencies
      working-directory: build      
      run: |
        export PATH=$PATH:$HOME/.local/bin
        conan install --build=missing ../
      
    - name: Configure
      working-directory: build
      run: cmake -DCMAKE_BUILD_TYPE=Release ../source
      
    - name: Build
      working-directory: build
      run: cmake --build . --config Release
      
    - name: Run unit tests
      working-directory: build
      run: build/bin/gsclib.test

    - name: Create Debian package
      working-directory: build
      run: cpack
    
    - name: Upload artifacts
      uses: actions/upload-artifact@v2
      with:
        path: build/*.deb
