name: build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      
    - name: Prepare tooling
      run: |
        sudo apt-get update
        sudo apt-get -y install gcc cmake make valgrind liblog4cxx-dev python3-pip python3-setuptools python3-wheel
        pip3 install conan
        mkdir build
        
    - name: Get dependencies
      working-directory: build      
      run: |
        export PATH=$PATH:$HOME/.local/bin
        conan install --build=missing ../ -s compiler.libcxx=libstdc++11
      
    - name: Configure
      working-directory: build
      run: cmake -DCMAKE_BUILD_TYPE=Release ../source
      
    - name: Build
      working-directory: build
      run: cmake --build . --config Release -- -j
      
    - name: Get integration test dependencies
      run: sudo apt-get -y install influxdb
      
    - name: Run gunit tests
      working-directory: build
      run: bin/gsclib.test
      
    - name: Run valgrind memory check
      working-directory: build
      run: |
        valgrind bin/gsclib.test \
          --leak-check=full \
          --show-reachable=yes \
          --track-origins=yes \
          --xml=yes --xml-file=valgrind.result.xml \
          --gtest_output=xml:test.result.xml

    - name: Create Debian package
      working-directory: build
      run: cpack
    
    - name: Upload artifacts
      uses: actions/upload-artifact@v2
      with:
        path: |
          build/*.deb
          build/*.result.xml
